INSERT INTO CUSTOMER(CUSTOMER_CNIC,CUSTOMER_NAME,CUSTOMER_CONTACT,CUSTOMER_ADDRESS)
VALUES('1273648292039','FAISAL','12345543213','LAHORE')
INSERT INTO MANUFACTURER(MANUFACTURER_ID,MANUFACTURER_NAME,MANUFACTURER_CONTACT,MANUFACTURER_EMAIL,MANUFACTURER_ADDRESS) 
VALUES('MF123','MERCEDES','23456789087','nkwjdnck@gmsil.com','London')
INSERT INTO MANUF_ORDER(ORDER_ID,EMPLOYEE_ID,CAR_ID,MANUFACTURER_ID,ORDER_DATE,BILL)
Values('MOD123','MG999','C3241','MF123',GETDATE(),3555000)
INSERT INTO STOCK_PAYMENT(ORDER_ID,PAYMENT_DATE)
VALUES('MOD123',GETDATE())
INSERT INTO Stock(Order_ID,REC_DATE)
VALUES('MOD123',GETDATE())
Insert into Account(MANF_Order,AMOUNT,IS_PAID,PAYMENT_DATE)
Values('MOD123',3500000,'TRUE',GETDATE())

INSERT INTO CUSTOMER_ORDER(ORDER_ID,EMPLOYEE_ID,CAR_ID,CUSTOMER_CNIC,ORDER_DATE,BILL)
Values('COD123','MG999','C1245','1273648292039',GETDATE(),3355000)

Insert into Account(Cust_Order,AMOUNT_RECEIVED,IS_PAID,PAYMENT_DATE) Values(@order,@amount,'FALSE',GETDATE())


SELECT *FROM CUSTOMER
SELECT *FROM EMPLOYEE
SELECT *FROM CAR
SELECT *FROM MANUFACTURER
SELECT *FROM STOCK
SELECT *FROM CUSTOMER_ORDER
SELECT *FROM MANUF_ORDER
SELECT *FROM STOCK_PAYMENT
SELECT *FROM SELL_PAYMENT
SELECT*FROM ACCOUNT

DELETE FROM ACCOUNT
DELETE FROM SELL_PAYMENT
DELETE FROM STOCK_PAYMENT
DELETE FROM STOCK
DELETE FROM CUSTOMER_ORDER
DELETE FROM MANUF_ORDER
DELETE FROM SELL_PAYMENT
DELETE FROM MANUFACTURER
DELETE FROM CAR
DELETE FROM CUSTOMER
DELETE FROM EMPLOYEE


SELECT CONVERT(DATE,GETDATE())
SELECT MAX(SUBSTRING(CUSTOMER_ORDER.ORDER_ID,4,LEN(CUSTOMER_ORDER.ORDER_ID))) FROM CUSTOMER_ORDER 
SELECT MAX(SUBSTRING(EMPLOYEE.EMPLOYEE_ID,3,LEN(EMPLOYEE.EMPLOYEE_ID))) FROM EMPLOYEE WHERE EMPLOYEE_DESIGNATION = 'SALESMAN'
DELETE FROM EMPLOYEE WHERE EMPLOYEE_DESIGNATION = 'SALESMAN'
UPDATE EMPLOYEE SET EMPLOYEE_STATUS = 'Working' WHERE EMPLOYEE_ID = 'MG999'




Select SELL_PAYMENT.ORDER_ID, CAR.CAR_NAME, EMPLOYEE.EMPLOYEE_NAME, CUSTOMER.CUSTOMER_NAME,CUSTOMER_ORDER.BILL, SELL_PAYMENT.PAYMENT_DATE 
from SELL_PAYMENT 
inner join CUSTOMER_ORDER on SELL_PAYMENT.ORDER_ID = CUSTOMER_ORDER.ORDER_ID
inner join CAR on CUSTOMER_ORDER.CAR_ID = CAR.CAR_ID
inner join EMPLOYEE on CUSTOMER_ORDER.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
inner join CUSTOMER on CUSTOMER_ORDER.CUSTOMER_CNIC = CUSTOMER.CUSTOMER_CNIC


Select	CAR.CAR_NAME,CAR.CAR_ID,CAR.CAR_MODEL,CAR.CAR_COMPANY
FROM MANUF_ORDER
INNER JOIN STOCK_PAYMENT ON MANUF_ORDER.ORDER_ID = STOCK_PAYMENT.ORDER_ID
INNER JOIN CAR ON MANUF_ORDER.CAR_ID = CAR.CAR_ID
WHERE STOCK_PAYMENT.ORDER_ID = 'MOD123'

Select	CAR.CAR_NAME, CAR.CAR_ID, CAR.CAR_MODEL, CAR.CAR_COMPANY FROM CUSTOMER_ORDER INNER JOIN SELL_PAYMENT
ON SELL_PAYMENT.ORDER_ID = CUSTOMER_ORDER.ORDER_ID
INNER JOIN CAR ON CUSTOMER_ORDER.CAR_ID = CAR.CAR_ID
WHERE CUSTOMER_ORDER.ORDER_ID = 'COD0001'

SELECT CUSTOMER.CUSTOMER_NAME, CUSTOMER.CUSTOMER_CNIC,CUSTOMER.CUSTOMER_CONTACT,CUSTOMER.CUSTOMER_ADDRESS
FROM SELL_PAYMENT
INNER JOIN CUSTOMER_ORDER ON SELL_PAYMENT.ORDER_ID = CUSTOMER_ORDER.ORDER_ID
INNER JOIN CUSTOMER ON CUSTOMER_ORDER.CUSTOMER_CNIC = CUSTOMER.CUSTOMER_CNIC
WHERE SELL_PAYMENT.ORDER_ID = 'COD0001'

SELECT MANUFACTURER.MANUFACTURER_NAME, MANUFACTURER.MANUFACTURER_ID, MANUFACTURER.MANUFACTURER_CONTACT , MANUFACTURER.MANUFACTURER_ADDRESS
FROM STOCK_PAYMENT
INNER JOIN MANUF_ORDER ON STOCK_PAYMENT.ORDER_ID = MANUF_ORDER.ORDER_ID
INNER JOIN MANUFACTURER ON MANUF_ORDER.MANUFACTURER_ID = MANUFACTURER.MANUFACTURER_ID
WHERE STOCK_PAYMENT.ORDER_ID = 'MOD123'

Select EMPLOYEE.EMPLOYEE_ID, EMPLOYEE.EMPLOYEE_NAME, EMPLOYEE.EMPLOYEE_CONTACT, EMPLOYEE.EMPLOYEE_DESIGNATION
FROM SELL_PAYMENT
INNER JOIN CUSTOMER_ORDER ON SELL_PAYMENT.ORDER_ID = CUSTOMER_ORDER.ORDER_ID
INNER JOIN EMPLOYEE ON CUSTOMER_ORDER.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
WHERE SELL_PAYMENT.ORDER_ID = 'COD0001'

SELECT MANUF_ORDER.ORDER_ID, MANUF_ORDER.BILL, MANUF_ORDER.ORDER_DATE 
FROM MANUF_ORDER 
INNER JOIN STOCK_PAYMENT ON STOCK_PAYMENT.ORDER_ID = MANUF_ORDER.ORDER_ID
WHERE STOCK_PAYMENT.ORDER_ID = 'MOD123'


Select ((sum(ACCOUNT.Amount) where ACCOUNT.IS_PAID = 'FALSE') - ( SELECT SUM(ACCOUNT.AMOUNT) WHERE ACCOUNT.IS_PAID = 'TRUE')) from account

SELECT SUM(ACCOUNT.AMOUNT) AS Spent FROM ACCOUNT WHERE ACCOUNT.IS_PAID = 'TRUE'
SELECT SUM(ACCOUNT.AMOUNT) AS Recieved FROM ACCOUNT WHERE ACCOUNT.IS_PAID = 'FALSE'

SELECT (SELECT SUM(ACCOUNT.AMOUNT) FROM ACCOUNT WHERE ACCOUNT.IS_PAID = 'TRUE') - (SELECT SUM(ACCOUNT.AMOUNT) FROM ACCOUNT WHERE ACCOUNT.IS_PAID = 'FALSE') AS 'DIFF'





Select EMPLOYEE.EMPLOYEE_ID, EMPLOYEE.EMPLOYEE_NAME, EMPLOYEE.EMPLOYEE_CONTACT, EMPLOYEE.EMPLOYEE_DESIGNATION 
 FROM SELL_PAYMENT
 INNER JOIN CUSTOMER_ORDER ON SELL_PAYMENT.ORDER_ID = CUSTOMER_ORDER.ORDER_ID
 INNER JOIN EMPLOYEE ON CUSTOMER_ORDER.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID 
 WHERE SELL_PAYMENT.ORDER_ID = 'COD0001'